In [2]:
import torch
import numpy as np
import torch.nn as nn

In [3]:
net=nn.Sequential(nn.Linear((2*2),2),nn.Softmax())

In [4]:
params=list(net.parameters())

print(params)

[Parameter containing:
tensor([[ 0.1384,  0.2972,  0.0030,  0.0048],
        [ 0.2515, -0.2844,  0.3692, -0.3041]], requires_grad=True), Parameter containing:
tensor([ 0.1049, -0.3625], requires_grad=True)]


In [5]:

input_data=torch.randn(2,2)

print(input_data)


tensor([[ 0.4571,  1.5962],
        [-0.5839,  1.7316]])


In [6]:
p=params[0].detach().numpy()

x=input_data.view(-1).detach().numpy()

b=params[1].detach().numpy()

res=np.dot(p,x)+b

In [7]:
res=torch.from_numpy(res)


In [8]:
res

tensor([ 0.6491, -1.4436])

In [9]:
np.exp(res)

tensor([1.9139, 0.2361])

In [10]:
out= net(input_data.view(-1))

target=torch.randn(2)

criterion=nn.MSELoss()

loss=criterion(out,target)

print(loss)

c:\users\k.shridhar\appdata\local\programs\python\python36\lib\site-packages\torch\nn\modules\container.py:92: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)


tensor(0.2332, grad_fn=<MseLossBackward>)


In [11]:
##After optimizing gradient descent

import torch.optim as optim

optimizer = optim.SGD(net.parameters(), lr=0.01)

optimizer.zero_grad()

loss=criterion(out,target)

loss.backward()

optimizer.step()    # Does the update



In [12]:
from fastai.vision import *
from fastai import *

### Fast AI practice for datablock API

In [18]:
coco=untar_data(URLs.COCO_TINY)

In [29]:
labels,bbox=get_annotations(coco/'train.json')

In [30]:
img2bbox = {img:bb for img, bb in zip(labels, bbox)}

In [34]:
get_y_func = lambda o:img2bbox[o.name]

In [41]:
data=(ObjectItemList.from_folder(coco).split_by_rand_pct().label_from_func(get_y_func))

In [44]:
data.databunch()

c:\users\k.shridhar\appdata\local\programs\python\python36\lib\site-packages\fastai\basic_data.py:271: UserWarning: It's not possible to collate samples of your dataset together in a batch.
  warn(message)


You can deactivate this warning by passing `no_check=True`.


ImageDataBunch;

Train: LabelList (160 items)
x: ObjectItemList
Image (3, 128, 128),Image (3, 128, 128),Image (3, 128, 128),Image (3, 128, 128),Image (3, 128, 128)
y: ObjectCategoryList
ImageBBox (128, 128),ImageBBox (128, 128),ImageBBox (128, 128),ImageBBox (128, 128),ImageBBox (128, 128)
Path: C:\Users\k.shridhar\.fastai\data\coco_tiny;

Valid: LabelList (40 items)
x: ObjectItemList
Image (3, 128, 128),Image (3, 128, 128),Image (3, 128, 128),Image (3, 128, 128),Image (3, 128, 128)
y: ObjectCategoryList
ImageBBox (128, 128),ImageBBox (128, 128),ImageBBox (128, 128),ImageBBox (128, 128),ImageBBox (128, 128)
Path: C:\Users\k.shridhar\.fastai\data\coco_tiny;

Test: None