In [15]:
%matplotlib inline
%config IPCompleter.greedy=True


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [4]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [11]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 2.0515e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


Construct a randomly initialized matrix:



In [13]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6636, 0.2170, 0.7836],
        [0.2245, 0.0879, 0.4169],
        [0.0176, 0.2175, 0.6088],
        [0.2144, 0.0501, 0.0201],
        [0.5461, 0.4205, 0.9511]])


Construct a matrix filled zeros and of dtype long:



In [14]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [16]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [17]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.4124, -0.7130,  0.5461],
        [ 0.7666, -0.4526, -1.6775],
        [ 0.5562, -0.5266,  1.8788],
        [-0.6196, -0.5033,  0.0927],
        [-0.7599,  1.4501,  0.6874]])


Get its size:



In [22]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [26]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 2.0987, -0.6101,  0.7461],
        [ 0.8170,  0.5298, -1.1443],
        [ 0.8530,  0.2645,  2.7829],
        [-0.0243,  0.0387,  0.4700],
        [ 0.0394,  2.3253,  0.7826]])


Addition: syntax 2



In [31]:
print(torch.add(x, y))

tensor([[ 2.0987, -0.6101,  0.7461],
        [ 0.8170,  0.5298, -1.1443],
        [ 0.8530,  0.2645,  2.7829],
        [-0.0243,  0.0387,  0.4700],
        [ 0.0394,  2.3253,  0.7826]])


Addition: providing an output tensor as argument



In [37]:
result = torch.empty(5, 3)
torch.add(x, y,out=result)
print(result)



tensor([[ 2.0987, -0.6101,  0.7461],
        [ 0.8170,  0.5298, -1.1443],
        [ 0.8530,  0.2645,  2.7829],
        [-0.0243,  0.0387,  0.4700],
        [ 0.0394,  2.3253,  0.7826]])


Addition: in-place



In [38]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 2.0987, -0.6101,  0.7461],
        [ 0.8170,  0.5298, -1.1443],
        [ 0.8530,  0.2645,  2.7829],
        [-0.0243,  0.0387,  0.4700],
        [ 0.0394,  2.3253,  0.7826]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [39]:
print(x[:, 1])

tensor([-0.7130, -0.4526, -0.5266, -0.5033,  1.4501])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [46]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(2, -1)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [47]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.9677])
-0.9677125811576843


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations (if the Torch Tensor is on CPU), and changing one will change
the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [48]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [49]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [50]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [51]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [52]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!